// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerticeMusicasWeb.Data;

#nullable disable

namespace VerticeMuiscaWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525024254_ProveedorEnMovimientoStock")]
    partial class ProveedorEnMovimientoStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("VerticeMusicasWeb.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idCategoria");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombreCategoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idDetalle");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProducto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idVenta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT")
                        .HasColumnName("precioUnitario");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idInventario");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.HasKey("IdInventario");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.MovimientoStock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idStock");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdInventario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idInventario");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProducto");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProveedor");

                    b.Property<decimal?>("PrecioUnitarioCompra")
                        .HasColumnType("TEXT")
                        .HasColumnName("precioUnitarioCompra");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stockMinimo");

                    b.HasKey("IdStock");

                    b.HasIndex("IdInventario");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProducto");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigoBarras");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idCategoria");

                    b.Property<bool>("ManejaStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manejaStock");

                    b.Property<string>("Marca")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProveedor");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdProveedor");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idVenta");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("metodoPago");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.HasKey("IdVenta");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.DetalleVenta", b =>
                {
                    b.HasOne("VerticeMusicasWeb.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VerticeMusicasWeb.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.MovimientoStock", b =>
                {
                    b.HasOne("VerticeMusicasWeb.Models.Inventario", "Inventario")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdInventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerticeMusicasWeb.Models.Producto", "Producto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VerticeMusicasWeb.Models.Proveedor", "Proveedor")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Inventario");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Producto", b =>
                {
                    b.HasOne("VerticeMusicasWeb.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Inventario", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Producto", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Proveedor", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("VerticeMusicasWeb.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
